/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package baseballstatapp;

import baseballstatapp.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Andy
 */
public class MainWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        pnlBatter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAbs = new javax.swing.JTextField();
        txt_B_Bbs = new javax.swing.JTextField();
        txtHbp = new javax.swing.JTextField();
        txtSfs = new javax.swing.JTextField();
        txtHrs = new javax.swing.JTextField();
        txtRbis = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt1b = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt2b = new javax.swing.JTextField();
        txt3b = new javax.swing.JTextField();
        pnlPitcher = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtInnings = new javax.swing.JTextField();
        txtWins = new javax.swing.JTextField();
        txtLosses = new javax.swing.JTextField();
        txtSvs = new javax.swing.JTextField();
        txtErs = new javax.swing.JTextField();
        txtKs = new javax.swing.JTextField();
        txt_P_Bbs = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_P_Hits = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnCalculate1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baseball Stat Calculator");
        setAlwaysOnTop(true);

        pnlBatter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batter", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel1.setText("ABs");

        jLabel3.setText("BBs");

        jLabel4.setText("HBP");

        jLabel5.setText("SFs");

        jLabel7.setText("HRs");

        jLabel8.setText("RBIs");

        txtAbs.setText("0");
        txtAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbsActionPerformed(evt);
            }
        });

        txt_B_Bbs.setText("0");
        txt_B_Bbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_B_BbsActionPerformed(evt);
            }
        });

        txtHbp.setText("0");

        txtSfs.setText("0");

        txtHrs.setText("0");
        txtHrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHrsActionPerformed(evt);
            }
        });

        txtRbis.setText("0");

        jLabel17.setText("1B");

        txt1b.setText("0");

        jLabel18.setText("2B");

        jLabel19.setText("3B");

        txt2b.setText("0");

        txt3b.setText("0");
        txt3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBatterLayout = new javax.swing.GroupLayout(pnlBatter);
        pnlBatter.setLayout(pnlBatterLayout);
        pnlBatterLayout.setHorizontalGroup(
            pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBatterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_B_Bbs, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHbp, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSfs, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1b, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2b, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3b, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRbis, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        pnlBatterLayout.setVerticalGroup(
            pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBatterLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_B_Bbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSfs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlBatterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRbis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPitcher.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pitcher", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel9.setText("Innings");

        jLabel10.setText("Wins");

        jLabel11.setText("Losses");

        jLabel12.setText("SVs");

        jLabel13.setText("ERs");

        jLabel14.setText("Ks");

        jLabel15.setText("BBs");

        txtInnings.setText("0");
        txtInnings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInningsActionPerformed(evt);
            }
        });

        txtWins.setText("0");

        txtLosses.setText("0");

        txtSvs.setText("0");
        txtSvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSvsActionPerformed(evt);
            }
        });

        txtErs.setText("0");
        txtErs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtErsActionPerformed(evt);
            }
        });

        txtKs.setText("0");
        txtKs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKsActionPerformed(evt);
            }
        });

        txt_P_Bbs.setText("0");
        txt_P_Bbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_P_BbsActionPerformed(evt);
            }
        });

        jLabel16.setText("Hits");

        txt_P_Hits.setText("0");
        txt_P_Hits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_P_HitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPitcherLayout = new javax.swing.GroupLayout(pnlPitcher);
        pnlPitcher.setLayout(pnlPitcherLayout);
        pnlPitcherLayout.setHorizontalGroup(
            pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPitcherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 101, Short.MAX_VALUE)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWins)
                    .addComponent(txtLosses)
                    .addComponent(txtSvs)
                    .addComponent(txtErs)
                    .addComponent(txt_P_Hits, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(txtKs)
                    .addComponent(txt_P_Bbs)
                    .addComponent(txtInnings)))
        );
        pnlPitcherLayout.setVerticalGroup(
            pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPitcherLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtInnings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtLosses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSvs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtErs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtKs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_P_Bbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPitcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_P_Hits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        btnCalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate.setText("Submit Batter");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnCalculate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate1.setText("Submit Pitcher");
        btnCalculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        txtName.setText("John doe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlBatter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPitcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(btnCalculate1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPitcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBatter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_P_HitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_P_HitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_P_HitsActionPerformed

    private void txtAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbsActionPerformed

    private void txt_B_BbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_B_BbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_B_BbsActionPerformed

    private void txtHrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHrsActionPerformed

    private void txtInningsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInningsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInningsActionPerformed

    private void txtSvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSvsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSvsActionPerformed

    private void txtErsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErsActionPerformed

    private void txtKsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKsActionPerformed

    private void txt_P_BbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_P_BbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_P_BbsActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:

        NumberFormat nf = NumberFormat.getInstance();
        
        try {
            
        //Batter
        double abs = Double.valueOf(txtAbs.getText());
        double B_bbs = Double.valueOf(txt_B_Bbs.getText());
        double hbp = Double.valueOf(txtHbp.getText());
        double sfs = Double.valueOf(txtSfs.getText());
        double singles = Double.valueOf(txt1b.getText());
        double doubles = Double.valueOf(txt2b.getText());
        double triples = Double.valueOf(txt3b.getText());
        double hrs = Double.valueOf(txtHrs.getText());
        double rbis = Double.valueOf(txtRbis.getText());
        String name = txtName.getText();
        
    
        //Batter categories
        double hits = (singles + doubles + triples + hrs);
        double avg = (hits / abs);
        double obp = (hits + B_bbs + hbp) / (abs + B_bbs + hbp + sfs);
        double slugging = ((1 * singles) + (2 * doubles) + (3 * triples) + (4 * hrs) / hits);
        double ops = (slugging + obp);
        double hrsPerAb = abs / hrs;
        
        
        //Validating all the of the entries
        if (abs == 0 || abs < 1 || Double.isNaN(abs)){
            throw new IllegalStatisticEntry();
        }
        if (B_bbs < 0 || Double.isNaN(B_bbs)){
            throw new IllegalStatisticEntry();
        }
        if (hbp < 0 || Double.isNaN(hbp)){
            throw new IllegalStatisticEntry();
        }
        if (sfs < 0 || Double.isNaN(sfs)){
            throw new IllegalStatisticEntry();
        }
        if (singles < 0 || Double.isNaN(singles)){
            throw new IllegalStatisticEntry();
        }
        if (doubles < 0 || Double.isNaN(doubles)){
            throw new IllegalStatisticEntry();
        }
        if (triples < 0 || Double.isNaN(triples)){
            throw new IllegalStatisticEntry();
        }
        if (hrs < 0 || Double.isNaN(hrs)){
            throw new IllegalStatisticEntry();
        }
        if (rbis < 0 || Double.isNaN(rbis)){
            throw new IllegalStatisticEntry();
        }
        //Name Validation
        if (name == null || name.length() == 0){
            throw new IllegalNameEntry();
        }
        for (char c : name.toCharArray()){
            if (Character.isDigit(c)){
                throw new IllegalNameEntry();
            }
        }

        //Displaying the information
        JOptionPane.showMessageDialog(this,  "BATTER:  " + name.toString() +  "\n\n"
                                    + "\n\nAvg: " + nf.format(avg)
                                    + "\nOBP: " + nf.format(obp)
                                    + "\nSlugging: " + nf.format(slugging)
                                    + "\nOPS: " + nf.format(ops)
                                    + "\nAB:HR " + nf.format(hrsPerAb));


        }
               //Exceptions
        catch (IllegalStatisticEntry ise){
            JOptionPane.showMessageDialog(this, ise.getMessage());
        }

        catch (IllegalNameEntry ine){
            JOptionPane.showMessageDialog(this, ine.getMessage());
        }

        catch (IllegalArgumentException iae){
            JOptionPane.showMessageDialog(this, "Invalid: NaN");
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txt3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3bActionPerformed

    private void btnCalculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate1ActionPerformed
        // TODO add your handling code here:

        NumberFormat nf = NumberFormat.getInstance();
        
            try {
        //Pitcher
        double innings = Double.valueOf(txtInnings.getText());
        double wins = Double.valueOf(txtWins.getText());
        double losses = Double.valueOf(txtLosses.getText());
        double svs = Double.valueOf(txtSvs.getText());
        double ers = Double.valueOf(txtErs.getText());
        double ks = Double.valueOf(txtKs.getText());
        double P_bbs = Double.valueOf(txt_P_Bbs.getText());
        double P_hits = Double.valueOf(txt_P_Hits.getText());
        String name = txtName.getText();
        
        //Pitcher categories
        double games = wins + losses;
        double winPercent = (wins / games) * 100;
        double era = innings / ers;
        double ksPer9 = 9 * (ks / innings);
        double bbsPer9 = 9 * (P_bbs / innings);
        double hitsPer9 = 9 * (P_hits / innings);
        double whip = (P_bbs + P_hits) / innings;
        
        
        if (innings == 0 || innings < 0 || Double.isNaN(innings)){
            throw new IllegalStatisticEntry();
        }
        
        if (wins < 0 || Double.isNaN(wins)){
            throw new IllegalStatisticEntry();
        }
        if (losses < 0 || Double.isNaN(losses)){
            throw new IllegalStatisticEntry();
        }
        if (svs < 0 || Double.isNaN(svs)){
            throw new IllegalStatisticEntry();
        }
        if (ers < 0 || Double.isNaN(ers)){
            throw new IllegalStatisticEntry();
        }
        if (ks < 0 || Double.isNaN(ks)){
            throw new IllegalStatisticEntry();
        }
        if (P_bbs < 0 || Double.isNaN(P_bbs)){
            throw new IllegalStatisticEntry();
        }
        if (P_hits < 0 || Double.isNaN(P_hits)){
            throw new IllegalStatisticEntry();
        }
        //Name Validation
        if (name == null || name.length() == 0){
            throw new IllegalNameEntry();
        }
                
        for (char c : name.toCharArray()){
            if (Character.isDigit(c)){
                throw new IllegalNameEntry();
            }
        }


        
        JOptionPane.showMessageDialog(this, "PITCHER:  " + name.toString() +  "\n\n"
                                    + "\n\nWin %: " + nf.format(winPercent)
                                    + "\nERA: " + nf.format(era)
                                    + "\nK:9 " + nf.format(ksPer9)
                                    + "\nBB:9 " + nf.format(bbsPer9)
                                    + "\nH:9 " + nf.format(hitsPer9)
                                    + "\nWHIP: " + nf.format(whip));


            }

            
        catch (IllegalStatisticEntry ise){
            JOptionPane.showMessageDialog(this, ise.getMessage());
        }

        catch (IllegalNameEntry ine){
            JOptionPane.showMessageDialog(this, ine.getMessage());
        }

        catch (IllegalArgumentException iae){
            JOptionPane.showMessageDialog(this, "Invalid: NaN");
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        
        
    }//GEN-LAST:event_btnCalculate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlBatter;
    private javax.swing.JPanel pnlPitcher;
    private javax.swing.JTextField txt1b;
    private javax.swing.JTextField txt2b;
    private javax.swing.JTextField txt3b;
    private javax.swing.JTextField txtAbs;
    private javax.swing.JTextField txtErs;
    private javax.swing.JTextField txtHbp;
    private javax.swing.JTextField txtHrs;
    private javax.swing.JTextField txtInnings;
    private javax.swing.JTextField txtKs;
    private javax.swing.JTextField txtLosses;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRbis;
    private javax.swing.JTextField txtSfs;
    private javax.swing.JTextField txtSvs;
    private javax.swing.JTextField txtWins;
    private javax.swing.JTextField txt_B_Bbs;
    private javax.swing.JTextField txt_P_Bbs;
    private javax.swing.JTextField txt_P_Hits;
    // End of variables declaration//GEN-END:variables


}
